version: '3.9'
services:
  postgres-db:
    image: postgres:13.3
    restart: always
    container_name: cherkasioblenergo-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cherkasioblenergo-db

#    volumes:
#      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
#      - db-data:/var/lib/postgresql/data